import { defineArrayMember, defineField, defineType } from "sanity";

export const operasyon = defineType({
  name: "operasyon",
  title: "Operasyon 4.0 page",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Title", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title.en" }, validation: (rule) => rule.required() }),
    defineField({ name: "heroEyebrow", title: "Hero eyebrow", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "heroTitle", title: "Hero title", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "heroSubtitle", title: "Hero subtitle", type: "localizedText", validation: (rule) => rule.required() }),
    defineField({ name: "heroCtaLabel", title: "Hero CTA label", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "heroCtaHref", title: "Hero CTA href", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "whatItReplacesHeading", title: "What it replaces heading", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "legacyStackLabel", title: "Legacy stack label", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "operasyonStackLabel", title: "Operasyon stack label", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({
      name: "legacyItems",
      title: "Legacy items",
      type: "array",
      of: [defineArrayMember({ type: "localizedString" })],
      validation: (rule) => rule.required().min(3),
    }),
    defineField({
      name: "operasyonItems",
      title: "Operasyon items",
      type: "array",
      of: [defineArrayMember({ type: "localizedString" })],
      validation: (rule) => rule.required().min(3),
    }),
    defineField({ name: "layersHeading", title: "Layers heading", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "mseHeading", title: "MSE heading", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "mseDescription", title: "MSE description", type: "localizedText", validation: (rule) => rule.required() }),
    defineField({ name: "embeddedFinanceHeading", title: "Embedded finance heading", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "embeddedFinanceDescription", title: "Embedded finance description", type: "localizedText", validation: (rule) => rule.required() }),
    defineField({ name: "marketplaceHeading", title: "Marketplace heading", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "marketplaceDescription", title: "Marketplace description", type: "localizedText", validation: (rule) => rule.required() }),
    defineField({
      name: "testimonials",
      title: "Testimonials",
      type: "array",
      of: [defineArrayMember({ type: "localizedText" })],
      validation: (rule) => rule.required().min(2).max(2),
    }),
    defineField({ name: "finalCtaLabel", title: "Final CTA label", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "finalCtaHref", title: "Final CTA href", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "formHeading", title: "Form heading", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "formSubmitLabel", title: "Form submit label", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "formNameLabel", title: "Form name label", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "formEmailLabel", title: "Form email label", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "formCompanyLabel", title: "Form company label", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "formCountryLabel", title: "Form country label", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "formMessageLabel", title: "Form message label", type: "localizedString", validation: (rule) => rule.required() }),
  ],
});
