import { defineArrayMember, defineField, defineType } from "sanity";

export const pipelineDetail = defineType({
  name: "pipelineDetail",
  title: "Pipeline detail",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Title", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title.en" }, validation: (rule) => rule.required() }),
    defineField({ name: "heroEyebrow", title: "Hero eyebrow", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "heroTitle", title: "Hero title", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "heroSubtitle", title: "Hero subtitle", type: "localizedText", validation: (rule) => rule.required() }),
    defineField({ name: "distinctionLabel", title: "Distinction label", type: "localizedString" }),
    defineField({ name: "distinctionText", title: "Distinction text", type: "localizedText" }),
    defineField({ name: "sectionOneHeading", title: "Section one heading", type: "localizedString" }),
    defineField({ name: "sectionTwoHeading", title: "Section two heading", type: "localizedString" }),
    defineField({ name: "sectionThreeHeading", title: "Section three heading", type: "localizedString" }),
    defineField({ name: "sectionFourHeading", title: "Section four heading", type: "localizedString" }),
    defineField({ name: "sectionFiveHeading", title: "Section five heading", type: "localizedString" }),
    defineField({
      name: "listOne",
      title: "List one",
      type: "array",
      of: [defineArrayMember({ type: "localizedString" })],
    }),
    defineField({
      name: "listTwo",
      title: "List two",
      type: "array",
      of: [defineArrayMember({ type: "localizedString" })],
    }),
    defineField({
      name: "listThree",
      title: "List three",
      type: "array",
      of: [defineArrayMember({ type: "localizedString" })],
    }),
    defineField({ name: "contentOne", title: "Content one", type: "localizedText" }),
    defineField({ name: "contentTwo", title: "Content two", type: "localizedText" }),
    defineField({ name: "contentThree", title: "Content three", type: "localizedText" }),
    defineField({ name: "ctaLabel", title: "CTA label", type: "localizedString", validation: (rule) => rule.required() }),
    defineField({ name: "ctaHref", title: "CTA href", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "formSubmitLabel", title: "Form submit label", type: "localizedString" }),
    defineField({ name: "formNameLabel", title: "Form name label", type: "localizedString" }),
    defineField({ name: "formEmailLabel", title: "Form email label", type: "localizedString" }),
    defineField({ name: "formCompanyLabel", title: "Form company label", type: "localizedString" }),
    defineField({ name: "formPhoneLabel", title: "Form phone label", type: "localizedString" }),
    defineField({ name: "formCountryLabel", title: "Form country label", type: "localizedString" }),
    defineField({ name: "formMessageLabel", title: "Form message label", type: "localizedString" }),
    defineField({ name: "formExtraOneLabel", title: "Form extra one label", type: "localizedString" }),
    defineField({ name: "formExtraTwoLabel", title: "Form extra two label", type: "localizedString" }),
  ],
});
